### ISSUE TITLE
Debug function

### ISSUE THREAD

**Issue by MADsti** [pixelcircuits/GBTool#1]
Hello, 
When i use the debug command, I get a lot of values, but for what are these values?
Do i get there the sha1_1k Information?
Thank you

**Comment by pixelcircuits** [comment]
It outputs if it thinks the GB detector switch is triggered (vs GBA) and then the first 400 bytes of data it read from the cartridge. You can check this data against the known ROM data to see if there are any particular pins that are consistently reading correctly/incorrectly

**Comment by MADsti** [comment]
Because I did not get any thumbnail, so I tried your tool, because i want to get out the sha_1k value but i did not find it.
Do you know what is the problem?
And can i read from the sha256 the sha_1k value?

**Comment by MADsti** [comment]
And i can Play the Games, but the Name is wrong and the are no thumbnails

**Comment by pixelcircuits** [comment]
It only supports thumbnails for the most common officially published games. You should be able to see the hashes with just the regular info command

**Comment by MADsti** [comment]
It is Pokémon Gold Version i just get the Sha1 Not the sha1_1k.
Or do you know how i get the sha_1k value out of the sha1 value?

**Comment by MADsti** [comment]
![image](https://user-images.githubusercontent.com/80861553/126826790-08434d14-d6b4-42a3-9107-d9e19d1c8a9b.jpeg)

**Comment by pixelcircuits** [comment]
That is the sha1_1k. The sha1 of the first 1024 bytes. You must have a cartridge with a different build than what the system has cataloged. You're sure it's not modded in any way?

**Comment by MADsti** [comment]
I tested this with 2 cartridges Pokémon Gold and Yellow. Always the Same. In the .json file at all german Games is just the sha1 value and often the sha1_1k is missing do you know the reason?

**Comment by pixelcircuits** [comment]
When building out that .json file, I had to find as many ROMs as I could to get the sha1_1k hashes. I tried to make it as complete as possible, but it's very difficult to obtain every ROM. There were lists online that included the sha1 hash of whole known ROMs but all the sha1_1k I had to compute myself. If you can fill in more entries for the .json file, please make a pull request or send me the ROMs and I can do it. You can calculate the sha1 hash of the whole ROM with this tool: [sha1](https://emn178.github.io/online-tools/sha1_checksum.html). Again, the sha1_1k is what is reported when running "GBTool info"

**Comment by MADsti** [comment]
I tried it today again, to put the sha1_1k info what i get Ouh of the info command to the .json file, but still i only got the roh name like: POKEMON_GAAULD and no thumbnails. I will send you the roms what i downloaded.

**Comment by MADsti** [comment]
Attached the ROM´s and the .json with the sha1_1k for Pokemon Goldene Edition German

Am 24. Juli 2021 um 16:10 schrieb PixelCircuits ***@***.***>:






When building out that .json file, I had to find as many ROMs as I could to get the sha1_1k hashes. I tried to make it as complete as possible, but it's very difficult to obtain every ROM. There were lists online that included the sha1 hash of whole known ROMs but all the sha1_1k I had to compute myself. If you can fill in more entries for the .json file, please make a pull request or send me the ROMs and I can do it. You can calculate the sha1 hash of the whole ROM with this tool: sha1. Again, the sha1_1k is what is reported when running "GBTool info"

**Comment by MADsti** [comment]
At which adress i can send the Roms?

**Comment by pixelcircuits** [comment]
The easiest way would probably be through messaging me privately on hackaday.io here: https://hackaday.io/project/171018-gameboy-console
